# Use an official Ubuntu base image
FROM ubuntu:latest

# Update the package lists and install dependencies
RUN apt-get update && apt-get install -y wget unzip

# Set the working directory
WORKDIR /app

# SUDO snap install chromium

RUN apt-get install libglib2.0-0 libnss3 libxcb1 chromium-bsu chromium-browser chromium-driver -y

# install manually all the missing libraries
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

# install chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# # Download the latest stable ChromeDriver version
# RUN CHROMEDRIVER_VERSION=$(wget -qO - https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
#     wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
#     unzip chromedriver_linux64.zip && \
#     rm chromedriver_linux64.zip

# # Make ChromeDriver executable
# RUN chmod +x chromedriver

# # Add the ChromeDriver binary to the PATH
# ENV PATH="/app:${PATH}"
# # ENV PATH="/usr/src:${PATH}"

# # # Verify ChromeDriver installation
# # RUN chromedriver --version

# # Optional: Clean up unnecessary packages
# RUN apt-get purge -y wget unzip && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# Update the package lists and install Python 3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip
# RUN apt-get update && apt-get install -y python3.8 python3-pip

# Optional: Set the default Python version to Python 3
RUN ln -s /usr/bin/python3 /usr/bin/python

# # Verify the Python installation
# RUN python --version

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip3 install --upgrade pip
COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

# copy project
COPY . .

