# Use an official Ubuntu as a parent image
FROM ubuntu:20.04
# latest
# FROM ubuntu:latest

# Set non-interactive mode during installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    unzip
    # unzip \
    # && rm -rf /var/lib/apt/lists/*

# # Install Chrome
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
#     echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
#     apt-get update && apt-get install -y google-chrome-stable && \
#     rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

RUN apt-get install -y libglib2.0-0 libnss3 libxcb1 chromium-bsu chromium-browser chromium-driver -y
# RUN apt-get install -y apt-get install  -y
RUN apt install chromium-browser -y

# RUN snap version
# RUN apt install snapd
# RUN snap install chromium

# RUN apt-get install gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils -y 

# # install chrome
# RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# ARG CHROME_VERSION="73.0.3683.20"

# RUN wget https://dl.google.com/linux/direct/google-chrome-stable_$CHROME_VERSION_amd64.deb
# RUN dpkg -i google-chrome-stable_$CHROME_VERSION_amd64.deb; apt-get -fy install


# RUN apt-get install libglib2.0-0 libnss3 libxcb1 chromium-browser chromium-driver -y
# RUN apt-get install libglib2.0-0 libnss3 libxcb1 -y

# Install Chrome WebDriver
# RUN CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1) && \
#     CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION") && \
#     wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
#     unzip chromedriver_linux64.zip -d /usr/local/bin && \
#     chmod +x /usr/local/bin/chromedriver && \
#     rm chromedriver_linux64.zip

# RUN CHROMEDRIVER_VERSION=$(wget -qO - https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
#     wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
#     unzip chromedriver_linux64.zip && \
#     rm chromedriver_linux64.zip

RUN wget "https://chromedriver.storage.googleapis.com/72.0.3626.69/chromedriver_linux64.zip" && \
    unzip chromedriver_linux64.zip && \
    rm chromedriver_linux64.zip

# RUN wget "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip" && \
#     unzip chromedriver_linux64.zip && \
#     rm chromedriver_linux64.zip

# Manually specify the ChromeDriver version
# # ENV CHROMEDRIVER_VERSION 117.0.5938.8800
# ENV CHROMEDRIVER_VERSION 116.0.5845.9600

# # Download and install Chrome WebDriver
# RUN wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
#     unzip chromedriver_linux64.zip -d /usr/local/bin && \
#     chmod +x /usr/local/bin/chromedriver && \
#     rm chromedriver_linux64.zip

# Make ChromeDriver executable
# RUN chmod +x chromedriver
RUN chmod +x /usr/bin/chromedriver

# RUN /usr/bin/chromedriver --log-path=/app/chromedriver.log

# Install required packages and dependencies
RUN apt-get update && apt-get install -y snapd

# Install Chromium as a Snap package
RUN snap install chromium

# Add the ChromeDriver binary to the PATH
# ENV PATH="/app:${PATH}"
ENV PATH="/usr/bin:${PATH}"

# Verify ChromeDriver installation
# RUN chromedriver --version

# Copy the requirements file into the container
# COPY ./requirements.txt .
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Copy the rest of your application's code into the container
COPY . .

# Set up a script to run your Selenium tests
CMD ["chromium", "python3", "worker.py"]
